import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';

import { Toaster } from '@/components/ui/sonner';
import { COOKIE } from '@/utils/constants';
import type { Theme } from '@/utils/contexts';

import Providers from './providers';

import '../assets/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const TOASTER_DURATION = 5000;

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = async ({ children }: RootLayoutProps) => {
  const themeCookie = cookies().get(COOKIE.THEME);
  const defaultTheme = (themeCookie?.value as Theme) ?? 'dark';

  return (
    <html className={defaultTheme} lang='en'>
      <head>
        <script src='https://accounts.google.com/gsi/client' />
      </head>
      <body className={`min-h-screen bg-background font-sans antialiased ${inter.className}`}>
        <Providers theme={{ defaultTheme }}>{children}</Providers>
        <Toaster duration={TOASTER_DURATION} />
      </body>
    </html>
  );
};

export default RootLayout;
