// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './apps/react-hooks/routes/__root'
import { Route as AuthImport } from './apps/react-hooks/routes/auth'
import { Route as IndexImport } from './apps/react-hooks/routes/index'

// Create Virtual Routes

const FigmaLazyImport = createFileRoute('/figma')()

// Create/Update Routes

const FigmaLazyRoute = FigmaLazyImport.update({
  path: '/figma',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./apps/react-hooks/routes/figma.lazy').then((d) => d.Route),
)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./apps/react-hooks/routes/auth.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./apps/react-hooks/routes/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/figma': {
      preLoaderRoute: typeof FigmaLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute,
  FigmaLazyRoute,
])
