// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './apps/react-hooks/routes/__root'
import { Route as AuthImport } from './apps/react-hooks/routes/auth'
import { Route as IndexImport } from './apps/react-hooks/routes/index'

// Create Virtual Routes

const GithubContextLazyImport = createFileRoute('/github-context')()
const GithubLazyImport = createFileRoute('/github')()

// Create/Update Routes

const GithubContextLazyRoute = GithubContextLazyImport.update({
  path: '/github-context',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./apps/react-hooks/routes/github-context.lazy').then((d) => d.Route),
)

const GithubLazyRoute = GithubLazyImport.update({
  path: '/github',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./apps/react-hooks/routes/github.lazy').then((d) => d.Route),
)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./apps/react-hooks/routes/auth.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./apps/react-hooks/routes/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/github': {
      preLoaderRoute: typeof GithubLazyImport
      parentRoute: typeof rootRoute
    }
    '/github-context': {
      preLoaderRoute: typeof GithubContextLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute,
  GithubLazyRoute,
  GithubContextLazyRoute,
])
